### ISSUE TITLE
cache permission errors in moin 1.9.10 / apache 2.2  / Centos6

### ISSUE THREAD

**Issue by robertosussex** [moinwiki/moin-1.9#81]
raise CacheError(str(err))
[Wed Jun 09 13:21:55 2021] [error] [client 5.80.25.21] CacheError: [Errno 13] Permission denied: '/srv/www/wikis/epp/data/cache/epp/drafts/1502880486.68.42100123PhE.tmp'

When I tried to change some lines in a page and "save changes"

Any idea?

Thanks

Roberto

**Comment by ThomasWaldmann** [comment]
this is usually caused by inconsistent permissions.

e.g. if you run your moin web process as user "moin", but run moin cli commands as user "root".

just always use the same user/group as the moin web process runs as.

one time fixing mixed up permissions is via `chown -R wanteduser.wantedgroup ...`.

**Comment by robertosussex** [comment]
Yes indeed! I had some directories with wrong ownership (root instaed of apache) etc
I corrected it and now it is fine
Many thanks
